from pydantic import BaseModel, Field


class Question(BaseModel):
    """A question generated by the assessment system."""

    content: str = Field(description="The question text presented to the student")
    topic: str = Field(description="The specific topic this question covers")
    difficulty: int = Field(ge=1, le=5, description="Difficulty level from 1 (easiest) to 5 (hardest)")
    expected_concepts: list[str] = Field(
        default_factory=list,
        description="Key concepts the student should demonstrate understanding of",
    )
